name: Presubmit

on: [pull_request]

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Query disk space
        run: |
          chkdsk
      - uses: actions/checkout@v1.0.0
      - name: Query disk space after checkout
        run: |
          chkdsk
      - name: Run build script
        run: |
          build\windows\build-github.bat presubmit
        shell: cmd
